### ISSUE TITLE
How to use your package for web?

### ISSUE THREAD

**Issue by bambinoua** [eneural-net/async_task#7]
I need an image decoding to be in isolate. Could you please to write a small example how I can do this using your package?

**Comment by gmpassos** [comment]
Hi. There's no Isolate in the browser.

The browser has Workers (https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) but dart doesn't have an official integration yet.

**Comment by bambinoua** [comment]
So why do you mark that your package is _compatible with a flutter on web platform_ if the package does not do this? 

What does it mean?

_This package brings asynchronous tasks and parallel executors (similar to classic thread pools) for all Dart platforms (JS/Web, Flutter, VM/Native)_.

It looks like in reality decoding image process will hangs the GUI on web platform because it will be executed in the main thread as regular `async` proceedure. So what is the benefit of your package?

**Comment by gmpassos** [comment]
### The package is marked correctly:

With the package `async_task` You can have `asynchronous tasks` in a web browser using the same syntax for all platforms. When running in a platform without Isolate the syntax is still the same.

Note that an `asynchronous` task is not the same as a `parallels` task. All Dart platforms supports asynchronous "functions" and `Future`s, so the package is marked in the correct way.

What you want is true parallel execution, through Isolate or native threads. Note that JS in the browser is designed to have a single thread to execute everything, it's a limitation imposed by the browser by design (on purpose).

**Comment by gmpassos** [comment]
You can take a look at:
https://pub.dev/packages/isolated_worker

That have some integration with Web Browser workers.

**Comment by eggzotic** [comment]
Thanks for asking @bambinoua , and for the clarification @gmpassos  - I was also misunderstanding that this package would help with getting some background-ability for Flutter-web apps. But in my tests I was always seeing "parallelism: 1" in the log output and the UI freezing while long-running computations were in-progress. So time to try something else, I guess.
